In [1]:
import numpy as np
import pandas as pd
import sympy as sp

# Definir objetos y sus clases
h = "Hola!!!"
print(type(h))

a = 2.56
print(type(a))

c = complex(2, 7)
print(type(c))

p = True
print(type(p))


<class 'str'>
<class 'float'>
<class 'complex'>
<class 'bool'>


In [2]:

# Operaciones aritméticas
print((11 + 2) * 3)
print(11 * 3 - 8 / 2 + np.sqrt(25))
print(5 ** 2)

b = 3 * np.arange(2, 7)
print(b)


39
34.0
25
[ 6  9 12 15 18]


In [11]:

# Trabajo con vectores
x = np.array([1, 7, 5, 4])  # Definir un array con valores específicos
y = np.array([2, 1, 8])  # Definir otro array con diferentes valores
z = np.concatenate((x, y))  # Concatenar los arrays x e y en un solo array
print(z)  # Imprimir el resultado de la concatenación

print(np.arange(2, 11, 2))  # Generar una secuencia de números pares desde 2 hasta 10
print(np.repeat(y, 2))  # Repetir cada elemento del array y dos veces
print(np.repeat(y, repeats=2))  # Otra forma de repetir cada elemento de y dos veces
print(np.repeat(y, repeats=3))  # Repetir cada elemento de y tres veces

print(2 + x)  # Sumar 2 a cada elemento del array x
print(x[:len(y)] + y)  # Sumar los primeros elementos de x con y
print(len(x))  # Obtener la longitud del array x
print(len(y))  # Obtener la longitud del array y

yn = np.append(y, 6)  # Agregar el valor 6 al final del array y
print(x + yn[:len(x)])  # Sumar x con los primeros elementos de yn
print(1 / x)  # Obtener el inverso de cada elemento de x
print(yn**2)  # Elevar al cuadrado cada elemento del array yn
print(np.sqrt(yn**2))  # Obtener la raíz cuadrada de cada elemento elevado al cuadrado


[1 7 5 4 2 1 8]
[ 2  4  6  8 10]
[2 2 1 1 8 8]
[2 2 1 1 8 8]
[2 2 2 1 1 1 8 8 8]
[3 9 7 6]
[ 3  8 13]
4
3
[ 3  8 13 10]
[1.         0.14285714 0.2        0.25      ]
[ 4  1 64 36]
[2. 1. 8. 6.]


In [12]:

# Selección de coordenadas de un vector
print(x[1])  # Obtener el segundo elemento del array x
print(x[[0, 2]])  # Obtener los elementos en las posiciones 0 y 2 de x
print(x[1:4])  # Obtener los elementos desde la posición 1 hasta la 3 de x
print(np.delete(x, [0, 2]))  # Eliminar los elementos en las posiciones 0 y 2 de x
print(x[x > 4])  # Obtener los elementos de x que sean mayores que 4
print(np.where(x > 4))  # Obtener los índices donde los elementos de x son mayores que 4
print(x[np.where(x > 4)])  # Obtener los elementos de x que cumplen la condición de ser mayores que 4
print(x[np.where((x > 1) & (x < 5))])  # Obtener los elementos de x que sean mayores que 1 y menores que 5
print(x[np.where((x > 1) | (x < 5))])  # Obtener los elementos de x que sean mayores que 1 o menores que 5



7
[1 5]
[7 5 4]
[7 4]
[7 5]
(array([1, 2]),)
[7 5]
[4]
[1 7 5 4]


In [13]:

# Trabajo con matrices
m = np.arange(1, 10).reshape(3, 3)  # Crear una matriz de 3x3 con valores del 1 al 9
print(m)  # Imprimir la matriz completa
print(m[0, 1])  # Obtener el valor en la fila 0, columna 1
print(m[0, :])  # Obtener la primera fila completa
print(m[:, 1])  # Obtener la segunda columna completa
print(m[m > 3])  # Obtener los elementos de la matriz mayores que 3
print(np.where(m > 3))  # Obtener los índices de los elementos mayores que 3


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3]
[2 5 8]
[4 5 6 7 8 9]
(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))


In [14]:

# Operaciones con matrices
print(np.matmul(m, m))  # Calcular el producto matricial de m por sí misma
print(m * m)  # Multiplicación elemento a elemento de la matriz m
print(m.T)  # Obtener la traspuesta de la matriz m
print(np.linalg.det(m))  # Calcular el determinante de la matriz m
print(np.diag(m))  # Extraer la diagonal de la matriz m
print(np.linalg.pinv(m))  # Calcular la pseudo-inversa de la matriz m



[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
0.0
[1 5 9]
[[-6.38888889e-01 -1.66666667e-01  3.05555556e-01]
 [-5.55555556e-02  4.20756436e-17  5.55555556e-02]
 [ 5.27777778e-01  1.66666667e-01 -1.94444444e-01]]


In [15]:

# Crear un DataFrame
e = np.arange(17, 21)  # Crear un array con edades de 17 a 20
g = np.tile(["f", "m"], 2)  # Repetir "f" y "m" dos veces para definir género
midata = pd.DataFrame({"edad": e, "sexo": g})  # Crear un DataFrame con edades y sexos
print(midata)  # Imprimir el DataFrame
print(midata.dtypes)  # Mostrar los tipos de datos de cada columna

midata["sexo"] = pd.Categorical(midata["sexo"], categories=["m", "f"])  # Convertir la columna "sexo" en una categoría ordenada
print(midata["edad"])  # Imprimir la columna de edades
print(midata.iloc[:, 0])  # Extraer la primera columna del DataFrame
print(midata.iloc[2, :])  # Extraer la tercera fila del DataFrame


   edad sexo
0    17    f
1    18    m
2    19    f
3    20    m
edad     int64
sexo    object
dtype: object
0    17
1    18
2    19
3    20
Name: edad, dtype: int64
0    17
1    18
2    19
3    20
Name: edad, dtype: int64
edad    19
sexo     f
Name: 2, dtype: object


In [16]:


# Cargar datos de iris y exportar
iris = load_iris()  # Cargar el conjunto de datos de iris
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)  # Convertirlo en un DataFrame
print(iris_df.info())  # Mostrar información del DataFrame

iris_df.to_csv("iris.csv", index=False)  # Guardar los datos en un archivo CSV sin incluir los índices

# Leer los datos
dat = pd.read_csv("iris.csv")  # Leer el archivo CSV almacenado previamente
print(dat.info())  # Mostrar información del DataFrame cargado

# Función condicional
a = 5  # Definir una variable a con valor 5
if a < 0:
    print("negativo")  # Si a es menor que 0, imprimir "negativo"
elif a < 3:
    print("a < 3")  # Si a es menor que 3, imprimir "a < 3"
else:
    print("a > 3")  # Si ninguna de las condiciones anteriores se cumple, imprimir "a > 3"


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB
None
a > 3
